// <auto-generated />
using DevicesSimulation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DevicesSimulation.Migrations
{
    [DbContext(typeof(DevicesContext))]
    [Migration("20180512123802_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("DevicesSimulation.Models.AirConditioner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<bool>("IsConect");

                    b.Property<bool>("IsWater");

                    b.Property<int>("Mode");

                    b.Property<string>("Name");

                    b.Property<bool>("Power");

                    b.Property<int>("Temperature");

                    b.Property<int>("TemperatureSensorReadings");

                    b.HasKey("Id");

                    b.ToTable("AirConditioners");
                });

            modelBuilder.Entity("DevicesSimulation.Models.DoorLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<bool>("IsConect");

                    b.Property<bool>("IsOpen");

                    b.Property<string>("Name");

                    b.Property<bool>("Power");

                    b.HasKey("Id");

                    b.ToTable("DoorLocks");
                });

            modelBuilder.Entity("DevicesSimulation.Models.Heater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<bool>("IsConect");

                    b.Property<string>("Name");

                    b.Property<bool>("Power");

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("Heaters");
                });

            modelBuilder.Entity("DevicesSimulation.Models.Lamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Brightness");

                    b.Property<string>("Company");

                    b.Property<bool>("IsConect");

                    b.Property<string>("Name");

                    b.Property<bool>("Power");

                    b.HasKey("Id");

                    b.ToTable("Lamps");
                });
#pragma warning restore 612, 618
        }
    }
}
