// <auto-generated />
using DevicesSimulation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DevicesSimulation.Migrations
{
    [DbContext(typeof(DevicesContext))]
    [Migration("20180509171819_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("DevicesSimulation.Models.Lamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Brightness");

                    b.Property<string>("Company");

                    b.Property<string>("Name");

                    b.Property<bool>("Power");

                    b.HasKey("Id");

                    b.ToTable("Lamps");
                });
#pragma warning restore 612, 618
        }
    }
}
